name: Build Windows EXE

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MSYS2 + SQLite
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-sqlite3

    - name: Build C executable
      shell: msys2 {0}
      run: |
        gcc --version
        gcc -o ares.exe main.c \
          -lsqlite3 \
          -lwininet -lshell32 -ladvapi32 \
          -mwindows -O2 -s

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ares-${{ github.run_id }}
        path: ares.exe
